name: CI Pipeline - Proyecto FEEOE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Validar sintaxis del archivo Docker Compose
        run: docker compose config

      - name: Chequeo estructural de carpetas
        run: |
          echo "Verificando consistencia del proyecto..."
          test -d App && echo "Carpeta App presente de forma correcta." || exit 1
